services:
  # Development services
  postgres:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: argus
      POSTGRES_PASSWORD: "L1gXxDNLx3_CpnFrxxcOjxBnowzw592i"
    volumes:
      - argus_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "4rEKng4zwVEr--Fdr-m3jZwQey4XPlNm"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: argus_test
      POSTGRES_PASSWORD: "VyhsjPAVDuz0TnaoMLkkPfbn6w0kIv_G"
    volumes:
      - argus_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "PiIPXNLwylWWN6-thwPxdCV_MIXBq8Xf"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  argus_data:
  argus_test_data:
